language: node_js
dist: focal
sudo: required
node_js: stable
services:
  - docker
install:
  - npm install
  - npm run build
  - ./compile-contracts.sh
  - npm run web3-generator

jobs:
  include:

  - stage: Test libraries
    name: "Test all libs"
    script:
    - docker run -d -p 8545:8545 -e ACCOUNTS_TO_CREATE=10 foamspace/cliquebait:v1.9.12
    - sleep 10
    - npm -s test

after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
