{ name = "web3-tests"
, dependencies =
  [ "aff"
  , "arrays"
  , "avar"
  , "bifunctors"
  , "bytestrings"
  , "console"
  , "effect"
  , "either"
  , "eth-core"
  , "foldable-traversable"
  , "identity"
  , "maybe"
  , "newtype"
  , "node-buffer"
  , "orders"
  , "parallel"
  , "partial"
  , "prelude"
  , "profunctor-lenses"
  , "quotient"
  , "spec"
  , "tagged"
  , "transformers"
  , "tuples"
  , "web3"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
